CREATE TABLE sys_security_user
(
    user_id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    username                VARCHAR(128) NOT NULL COMMENT '用户名（账号）',
    birth_date              DATE COMMENT '生日',
    sex                     TINYINT  DEFAULT 0 COMMENT '性别 0未知 1男 2女 9未说明/其他',
    phone                   VARCHAR(64) COMMENT '电话号码',
    id_card                 VARCHAR(32) COMMENT '身份证号码',
    email                   VARCHAR(128) COMMENT '邮箱',
    password                VARCHAR(255) COMMENT '密码',
    avatar                  LONGTEXT COMMENT '头像',
    address                 VARCHAR(1024) COMMENT '地址',
    username_cn             VARCHAR(128) COMMENT '姓名（中文）',
    username_en             VARCHAR(128) COMMENT '姓名（英文）',
    nick_name               VARCHAR(128) COMMENT '昵称',
    account_non_expired     TINYINT  DEFAULT 1 COMMENT '是否未过期 0过期 1未过期',
    account_non_locked      TINYINT  DEFAULT 1 COMMENT '是否未锁定 0锁定 1未锁定',
    credentials_non_expired TINYINT  DEFAULT 1 COMMENT '是否密钥未过期 0过期 1未过期',
    pwd_salt                VARCHAR(128) COMMENT '密码随机盐',
    map_code                VARCHAR(128) COMMENT '第三方映射码',
    sp_status               VARCHAR(64) COMMENT '审批状态',
    status                  TINYINT COMMENT '用户状态',
    create_by               VARCHAR(128) COMMENT '创建人',
    create_name             VARCHAR(128) COMMENT '创建人姓名',
    create_time             DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by               VARCHAR(128) COMMENT '更新人',
    update_name             VARCHAR(128) COMMENT '更新人姓名',
    last_update_time        DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_enabled              TINYINT  DEFAULT 1 COMMENT '是否启用 1启用 0禁用',
    is_deleted              TINYINT  DEFAULT 0 COMMENT '是否删除 1已删除 0未删除',
    INDEX idx_username (username),
    INDEX idx_phone (phone),
    INDEX idx_email (email),
    INDEX idx_create_time (create_time),
    INDEX idx_last_update_time (last_update_time)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT ='用户信息表';