-- 创建消息表
CREATE TABLE SYS_LOCAL_MESSAGE
(
    -- 消息 ID，唯一标识一条消息，作为主键
    MSG_ID        VARCHAR2(255) NOT NULL,
    -- 业务相关的唯一键，用于标识业务操作
    BUSINESS_KEY  VARCHAR2(255),
    BUSINESS_NAME VARCHAR2(255),
    -- 消息的具体内容，可存储任意长度的文本
    CONTENT       CLOB,
    -- 处理该消息所使用的 Bean 名称
    BEAN_NAME     VARCHAR2(255),
    -- 处理该消息所调用的 Bean 方法
    BEAN_METHOD   VARCHAR2(255),
    -- 消息处理失败后的重试次数
    RETRY_COUNT   NUMBER(10),
    -- 消息当前的处理状态，使用整数表示不同状态
    STATUS        NUMBER(10),
    -- 消息记录创建的日期和时间
    CREATE_DATE   TIMESTAMP,
    -- 消息记录最后更新的日期和时间
    UPDATE_DATE   TIMESTAMP,
    -- 消息处理过程中产生的错误信息
    ERROR_MESSAGE CLOB,
    -- 标记消息是否被冻结，使用字符串表示冻结状态
    IS_FREEZE     VARCHAR2(255),
    -- 设置 MSG_ID 为主键
    CONSTRAINT PK_SYS_LOCAL_MESSAGE PRIMARY KEY (MSG_ID)
);

-- 添加字段注释
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.MSG_ID IS '消息 ID';
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.BUSINESS_KEY IS '业务键';
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.BUSINESS_NAME IS '业务描述';
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.CONTENT IS '消息内容';
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.BEAN_NAME IS 'Bean 名称';
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.BEAN_METHOD IS 'Bean 方法';
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.RETRY_COUNT IS '重试次数';
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.STATUS IS '消息状态';
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.CREATE_DATE IS '创建日期';
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.UPDATE_DATE IS '更新日期';
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.ERROR_MESSAGE IS '错误消息';
COMMENT ON COLUMN SYS_LOCAL_MESSAGE.IS_FREEZE IS '是否冻结';

-- 添加表注释
COMMENT ON TABLE SYS_LOCAL_MESSAGE IS '本地信息表';