easy4j:
  server-name: 999-service
  nacos-url: 127.0.0.1:8848@nacos:nacos
  nacos-config-strict: true
  data-ids: "999-service.properties?group=DEV_TEST,999-service.properties?group=DEFAULT_GROUP"
  env: prod
  nacos-config-file-extension: yml
  # 999-service-prod.yaml
  # group namespace data-id
#  data-source-url: jdbc:postgresql://localhost:5432/test@root:123456


