spring:
  application:
    name: my-service
  profiles:
    active: dev
  config:
    import: "optional:nacos:${spring.application.name}-${spring.profiles.active}.yml"
  cloud:
    nacos:
      discovery:
        namespace: public  # 命名空间（可选）
        group: DEFAULT_GROUP          # 配置组（可选）
      config:
        namespace: public  # 命名空间（可选）
        group: DEFAULT_GROUP          # 配置组（可选）
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
