spring:
  application:
    name: my-service
  profiles:
    active: dev
  config:
    import: "nacos:${spring.application.name}-${spring.profiles.active}.properties"
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848  # Nacos 服务器地址
        namespace: public  # 命名空间（可选）
        group: DEFAULT_GROUP          # 配置组（可选）