package easy4j.infra.dbaccess.orm.runner;

import java.sql.*;
import java.util.function.BiConsumer;

/**
 * 数据库执行工具类
 * 提供通用的连接和执行方法
 *
 * @author bokun.li
 * @since 2.1.5.8
 */
public class ExecutorUtil {
    /**
     * 执行查询操作
     *
     * @param connection 数据库连接
     * @param sql        SQL语句
     * @param executor   参数设置执行器
     * @return 查询结果集
     * @throws SQLException 数据库异常
     */
    public static PsRes executeQuery(
            Connection connection,
            String sql,
            Executor executor) throws SQLException {
        PreparedStatement pstmt = connection.prepareStatement(sql);
        ResultSet resultSet = executor.executeQuery(pstmt);
        return new PsRes().setResultSet(resultSet).setStatement(pstmt);
    }

    /**
     * 执行更新操作
     *
     * @param connection        数据库连接
     * @param sql               SQL语句
     * @param executor          参数设置执行器
     * @param autoGeneratedKeys 是否返回自增数据 0 不设置
     *                          {@code Statement.RETURN_GENERATED_KEYS} or
     *                          {@code Statement.NO_GENERATED_KEYS}
     * @return 影响的行数
     * @throws SQLException 数据库异常
     */
    public static PsRes executeUpdate(
            Connection connection,
            String sql,
            Executor executor,
            Integer autoGeneratedKeys
    ) throws SQLException {
        if (autoGeneratedKeys != null && autoGeneratedKeys > 0) {
            PreparedStatement pstmt = connection.prepareStatement(sql, autoGeneratedKeys);
            return new PsRes().setStatement(pstmt).setEffectRows(executor.executeUpdate(pstmt));
        } else {
            PreparedStatement pstmt = connection.prepareStatement(sql);
            return new PsRes().setStatement(pstmt).setEffectRows(executor.executeUpdate(pstmt));
        }
    }

    /**
     * 执行批处理操作
     *
     * @param connection 数据库连接
     * @param sql        SQL语句
     * @param executors  参数设置执行器数组
     * @return 每次执行影响的行数数组
     * @throws SQLException 数据库异常
     */
    public static PsRes executeBatch(
            Connection connection,
            String sql,
            Executor[] executors) throws SQLException {
        PreparedStatement pstmt = connection.prepareStatement(sql);
        for (Executor executor : executors) {
            executor.setParameters(pstmt);
            pstmt.addBatch();
        }
        int totalCount = 0;
        int[] ints = pstmt.executeBatch();
        for (int result : ints) {
            if (result > 0) totalCount += result;
        }
        return new PsRes().setStatement(pstmt).setEffectRows(totalCount);
    }

    /**
     * 执行事务性批处理
     *
     * @param connection    数据库连接
     * @param sql           SQL语句
     * @param executors     参数设置执行器数组
     * @param batchSize     每次执行的批处理大小
     * @param batchCallback 回调这一批次的条数，以及当前进度
     * @return 总的影响行数
     * @throws SQLException 数据库异常
     */
    public static PsRes executeBatchWithTransaction(
            Connection connection,
            String sql,
            Executor[] executors,
            int batchSize,
            BiConsumer<Integer, Integer> batchCallback
    ) throws SQLException {

        boolean autoCommit = connection.getAutoCommit();
        int totalCount = 0;
        PreparedStatement pstmt = connection.prepareStatement(sql);
        try {
            connection.setAutoCommit(false);
            int count = 0;
            for (Executor executor : executors) {
                executor.setParameters(pstmt);
                pstmt.addBatch();
                count++;
                // 达到批处理大小时执行
                if (count >= batchSize) {
                    int[] results = pstmt.executeBatch();
                    pstmt.clearBatch();
                    int theBatchNumber = 0;
                    for (int result : results) {

                        if (result > 0) {
                            totalCount += result;
                            theBatchNumber += result;
                        }else if(result == Statement.SUCCESS_NO_INFO){
                            totalCount += 1;
                            theBatchNumber += 1;
                        }
                    }
                    if (batchCallback != null) {
                        batchCallback.accept(count, theBatchNumber);
                    }
                    count = 0;
                }
            }
            // 执行剩余的
            if (count > 0) {
                int[] results = pstmt.executeBatch();
                int theBatchNumber = 0;
                for (int result : results) {
                    theBatchNumber += result;
                    if (result > 0) {
                        totalCount += result;
                        theBatchNumber += result;
                    }else if(result == Statement.SUCCESS_NO_INFO){
                        totalCount += 1;
                        theBatchNumber += 1;
                    }
                }
                if (batchCallback != null) {
                    batchCallback.accept(count, theBatchNumber);
                }
            }
            connection.commit();
        } catch (SQLException e) {
            connection.rollback();
            throw e;
        } finally {
            connection.setAutoCommit(autoCommit);
        }
        return new PsRes().setStatement(pstmt).setEffectRows(totalCount);
    }
}