easy4j.server-port=9200
spring.application.name=sba
spring.boot.admin.ui.title=SBA
spring.boot.admin.context-path=/easy4j
spring.security.user.name=easy4j
spring.security.user.password=easy123
spring.security.user.roles=ADMIN
spring.boot.admin.ui.brand=<img src="assets/img/icon-spring-boot-admin.svg"><span>SBA</span>