CREATE TABLE SYS_TCC_FENCE_LOG
(
    XID          VARCHAR2(128) NOT NULL,
    BRANCH_ID    NUMBER(19)    NOT NULL,
    ACTION_NAME  VARCHAR2(64)  NOT NULL,
    STATUS       NUMBER(3)     NOT NULL,
    GMT_CREATE   TIMESTAMP(3)  NOT NULL,
    GMT_MODIFIED TIMESTAMP(3)  NOT NULL,
    PRIMARY KEY (XID, BRANCH_ID)
);
CREATE INDEX IDX_GMT_MODIFIED ON SYS_TCC_FENCE_LOG (GMT_MODIFIED);
CREATE INDEX IDX_STATUS ON SYS_TCC_FENCE_LOG (STATUS);