-- -------------------------------- THE SCRIPT USED FOR TCC FENCE  --------------------------------
CREATE TABLE IF NOT EXISTS PUBLIC.SYS_TCC_FENCE_LOG
(
    XID          VARCHAR(128) NOT NULL,
    BRANCH_ID    BIGINT       NOT NULL,
    ACTION_NAME  VARCHAR(64)  NOT NULL,
    STATUS       SMALLINT     NOT NULL,
    GMT_CREATE   TIMESTAMP(3) NOT NULL,
    GMT_MODIFIED TIMESTAMP(3) NOT NULL,
    CONSTRAINT PK_SYS_TCC_FENCE_LOG PRIMARY KEY (XID, BRANCH_ID)
);
CREATE INDEX IDX_GMT_MODIFIED ON PUBLIC.SYS_TCC_FENCE_LOG (GMT_MODIFIED);
CREATE INDEX IDX_STATUS ON PUBLIC.SYS_TCC_FENCE_LOG (STATUS);