CREATE TABLE [DBO].[SYS_TCC_FENCE_LOG]
(
    [XID]          VARCHAR(128) NOT NULL,
    [BRANCH_ID]    BIGINT       NOT NULL,
    [ACTION_NAME]  VARCHAR(64)  NOT NULL,
    [STATUS]       TINYINT      NOT NULL,
    [GMT_CREATE]   DATETIME2(3) NOT NULL,
    [GMT_MODIFIED] DATETIME2(3) NOT NULL,
    PRIMARY KEY CLUSTERED ([XID], [BRANCH_ID])
);

CREATE NONCLUSTERED INDEX [IDX_GMT_MODIFIED] ON [DBO].[SYS_TCC_FENCE_LOG] ([GMT_MODIFIED]);
CREATE NONCLUSTERED INDEX [IDX_STATUS] ON [DBO].[SYS_TCC_FENCE_LOG] ([STATUS]);

EXEC SP_ADDEXTENDEDPROPERTY
     @NAME = N'MS_DESCRIPTION',
     @VALUE = N'GLOBAL ID',
     @LEVEL0TYPE = N'SCHEMA', @LEVEL0NAME = N'DBO',
     @LEVEL1TYPE = N'TABLE', @LEVEL1NAME = N'SYS_TCC_FENCE_LOG',
     @LEVEL2TYPE = N'COLUMN', @LEVEL2NAME = N'XID';