CREATE TABLE SYS_SECURITY_SESSION
(
    ID                  BIGINT PRIMARY KEY,
    USER_NAME           NVARCHAR(255),
    USER_ID             BIGINT,
    USER_NAME_CN        NVARCHAR(255),
    USER_NAME_EN        NVARCHAR(255),
    NICK_NAME           NVARCHAR(255),
    SHA_TOKEN           NVARCHAR(255),
    JWT_TOKEN           NVARCHAR(MAX),
    SALT                NVARCHAR(255),
    IP                  NVARCHAR(45),
    DEVICE_INFO         NVARCHAR(255),
    LOGIN_DATE_TIME     DATETIME2,
    LOGOUT_DATE_TIME    DATETIME2,
    IS_INVALID          INT,
    EXPIRE_TIME_SECONDS BIGINT,
    DEPT_CODE           NVARCHAR(255),
    DEPT_NAME           NVARCHAR(255),
    EXT_MAP             NVARCHAR(MAX)
);

CREATE INDEX IDX_SYS_SECURITY_SESSION_USER_NAME ON SYS_SECURITY_SESSION (USER_NAME);
CREATE INDEX IDX_SYS_SECURITY_SESSION_USER_ID ON SYS_SECURITY_SESSION (USER_ID);
CREATE INDEX IDX_SYS_SECURITY_SESSION_SHA_TOKEN ON SYS_SECURITY_SESSION (SHA_TOKEN);


CREATE TABLE SYS_SECURITY_USER
(
    USER_ID                 BIGINT PRIMARY KEY,
    USERNAME                NVARCHAR(255) UNIQUE,
    PASSWORD                NVARCHAR(255),
    USERNAME_CN             NVARCHAR(255),
    USERNAME_EN             NVARCHAR(255),
    NICK_NAME               NVARCHAR(255),
    ACCOUNT_NON_EXPIRED     BIT,
    ACCOUNT_NON_LOCKED      BIT,
    CREDENTIALS_NON_EXPIRED BIT,
    ENABLED                 BIT,
    PWD_SALT                NVARCHAR(255),
    CREATE_DATE             DATETIME2,
    DEPT_CODE               NVARCHAR(255),
    DEPT_NAME               NVARCHAR(255),
    UPDATE_DATE             DATETIME2
);

CREATE UNIQUE INDEX IDX_SYS_SECURITY_USER_USERNAME ON SYS_SECURITY_USER (USERNAME);