CREATE TABLE SYS_SECURITY_SESSION
(
    SESSION_ID          BIGINT PRIMARY KEY,
    USER_NAME           NVARCHAR(255),
    USER_ID             BIGINT,
    USER_NAME_CN        NVARCHAR(255),
    USER_NAME_EN        NVARCHAR(255),
    NICK_NAME           NVARCHAR(255),
    SHA_TOKEN           NVARCHAR(255),
    JWT_TOKEN           NVARCHAR(MAX),
    JWT_SALT            NVARCHAR(255),
    IP                  NVARCHAR(45),
    DEVICE_INFO         NVARCHAR(255),
    LOGIN_DATE_TIME     DATETIME2,
    LOGOUT_DATE_TIME    DATETIME2,
    IS_INVALID          INT,
    EXPIRE_TIME_SECONDS BIGINT,
    DEPT_CODE           NVARCHAR(255),
    DEPT_NAME           NVARCHAR(255),
    EXT_MAP             NVARCHAR(MAX)
);

CREATE INDEX IDX_SYS_SECURITY_SESSION_USER_NAME ON SYS_SECURITY_SESSION (USER_NAME);
CREATE INDEX IDX_SYS_SECURITY_SESSION_USER_ID ON SYS_SECURITY_SESSION (USER_ID);
CREATE INDEX IDX_SYS_SECURITY_SESSION_SHA_TOKEN ON SYS_SECURITY_SESSION (SHA_TOKEN);

