CREATE TABLE SYS_SECURITY_SESSION
(
    ID                  BIGINT PRIMARY KEY,
    USER_NAME           VARCHAR(255),
    USER_ID             BIGINT,
    USER_NAME_CN        VARCHAR(255),
    USER_NAME_EN        VARCHAR(255),
    NICK_NAME           VARCHAR(255),
    SHA_TOKEN           VARCHAR(255),
    JWT_TOKEN           TEXT,
    SALT                VARCHAR(255),
    IP                  VARCHAR(45),
    DEVICE_INFO         VARCHAR(255),
    LOGIN_DATE_TIME     DATETIME,
    LOGOUT_DATE_TIME    DATETIME,
    IS_INVALID          INT,
    EXPIRE_TIME_SECONDS BIGINT,
    DEPT_CODE           VARCHAR(255),
    DEPT_NAME           VARCHAR(255),
    EXT_MAP             JSON
);

CREATE INDEX IDX_SYS_SECURITY_SESSION_USER_NAME ON SYS_SECURITY_SESSION (USER_NAME);
CREATE INDEX IDX_SYS_SECURITY_SESSION_USER_ID ON SYS_SECURITY_SESSION (USER_ID);
CREATE INDEX IDX_SYS_SECURITY_SESSION_SHA_TOKEN ON SYS_SECURITY_SESSION (SHA_TOKEN);


CREATE TABLE SYS_SECURITY_USER
(
    USER_ID                 BIGINT PRIMARY KEY,
    USERNAME                VARCHAR(255) UNIQUE,
    PASSWORD                VARCHAR(255),
    USERNAME_CN             VARCHAR(255),
    USERNAME_EN             VARCHAR(255),
    NICK_NAME               VARCHAR(255),
    ACCOUNT_NON_EXPIRED     TINYINT(1),
    ACCOUNT_NON_LOCKED      TINYINT(1),
    CREDENTIALS_NON_EXPIRED TINYINT(1),
    ENABLED                 TINYINT(1),
    PWD_SALT                VARCHAR(255),
    CREATE_DATE             DATETIME,
    DEPT_CODE               VARCHAR(255),
    DEPT_NAME               VARCHAR(255),
    UPDATE_DATE             DATETIME
);

CREATE UNIQUE INDEX IDX_SYS_SECURITY_USER_USERNAME ON SYS_SECURITY_USER (USERNAME);