CREATE TABLE SYS_SECURITY_SESSION
(
    ID                  NUMBER(19) PRIMARY KEY,
    USER_NAME           VARCHAR2(255),
    USER_ID             NUMBER(19),
    USER_NAME_CN        VARCHAR2(255),
    USER_NAME_EN        VARCHAR2(255),
    NICK_NAME           VARCHAR2(255),
    SHA_TOKEN           VARCHAR2(255),
    JWT_TOKEN           CLOB,
    SALT                VARCHAR2(255),
    IP                  VARCHAR2(45),
    DEVICE_INFO         VARCHAR2(255),
    LOGIN_DATE_TIME     TIMESTAMP,
    LOGOUT_DATE_TIME    TIMESTAMP,
    IS_INVALID          NUMBER(10),
    EXPIRE_TIME_SECONDS NUMBER(19),
    DEPT_CODE           VARCHAR2(255),
    DEPT_NAME           VARCHAR2(255),
    EXT_MAP             CLOB
);

CREATE INDEX IDX_SYS_SECURITY_SESSION_USER_NAME ON SYS_SECURITY_SESSION (USER_NAME);
CREATE INDEX IDX_SYS_SECURITY_SESSION_USER_ID ON SYS_SECURITY_SESSION (USER_ID);
CREATE INDEX IDX_SYS_SECURITY_SESSION_SHA_TOKEN ON SYS_SECURITY_SESSION (SHA_TOKEN);


CREATE TABLE SYS_SECURITY_USER
(
    USER_ID                 NUMBER(19) PRIMARY KEY,
    USERNAME                VARCHAR2(255) UNIQUE,
    PASSWORD                VARCHAR2(255),
    USERNAME_CN             VARCHAR2(255),
    USERNAME_EN             VARCHAR2(255),
    NICK_NAME               VARCHAR2(255),
    ACCOUNT_NON_EXPIRED     NUMBER(1),
    ACCOUNT_NON_LOCKED      NUMBER(1),
    CREDENTIALS_NON_EXPIRED NUMBER(1),
    ENABLED                 NUMBER(1),
    PWD_SALT                VARCHAR2(255),
    CREATE_DATE             TIMESTAMP,
    DEPT_CODE               VARCHAR2(255),
    DEPT_NAME               VARCHAR2(255),
    UPDATE_DATE             TIMESTAMP
);

CREATE UNIQUE INDEX IDX_SYS_SECURITY_USER_USERNAME ON SYS_SECURITY_USER (USERNAME);