CREATE TABLE SYS_SECURITY_SESSION
(
    SESSION_ID          BIGINT PRIMARY KEY,
    USER_NAME           VARCHAR(255),
    USER_ID             BIGINT,
    USER_NAME_CN        VARCHAR(255),
    USER_NAME_EN        VARCHAR(255),
    NICK_NAME           VARCHAR(255),
    SHA_TOKEN           VARCHAR(255),
    JWT_TOKEN           TEXT,
    JWT_SALT            VARCHAR(255),
    IP                  VARCHAR(45),
    DEVICE_INFO         VARCHAR(255),
    LOGIN_DATE_TIME     TIMESTAMP,
    LOGOUT_DATE_TIME    TIMESTAMP,
    IS_INVALID          INT,
    EXPIRE_TIME_SECONDS BIGINT,
    DEPT_CODE           VARCHAR(255),
    DEPT_NAME           VARCHAR(255),
    EXT_MAP             JSONB
);

CREATE INDEX IDX_SYS_SECURITY_SESSION_USER_NAME ON SYS_SECURITY_SESSION (USER_NAME);
CREATE INDEX IDX_SYS_SECURITY_SESSION_USER_ID ON SYS_SECURITY_SESSION (USER_ID);
CREATE INDEX IDX_SYS_SECURITY_SESSION_SHA_TOKEN ON SYS_SECURITY_SESSION (SHA_TOKEN);


