create TABLE SYS_LOCK
(
    ID          VARCHAR(36) NOT NULL PRIMARY KEY,
    CREATE_DATE TIMESTAMP,
    EXPIRE_DATE TIMESTAMP,
    REMARK      VARCHAR(500)

);
COMMENT ON TABLE SYS_LOCK IS '系统锁';
COMMENT ON COLUMN SYS_LOCK.ID IS '主键';
COMMENT ON COLUMN SYS_LOCK.CREATE_DATE IS '操作时间';
COMMENT ON COLUMN SYS_LOCK.EXPIRE_DATE IS '过期时间';
COMMENT ON COLUMN SYS_LOCK.REMARK IS '备注';
CREATE INDEX IDX_SYS_LOCK_CREATE_DATE ON SYS_LOCK (CREATE_DATE);
