CREATE TABLE SYS_LOCK
(
    ID          VARCHAR(36) PRIMARY KEY COMMENT '主键',
    CREATE_DATE TIMESTAMP COMMENT '操作时间',
    EXPIRE_DATE TIMESTAMP COMMENT '过期时间',
    REMARK      VARCHAR(36) COMMENT '备注'
);
CREATE INDEX IDX_SYS_LOCK_CREATE_DATE ON SYS_LOCK (CREATE_DATE);
