CREATE TABLE IF NOT EXISTS SYS_LOCK
(
    ID           VARCHAR(36) PRIMARY KEY COMMENT '主键',
    CREATE_DATE  DATETIME COMMENT '操作时间',
    EXPIRE_DATE  DATETIME COMMENT '过期时间',
    REMARK  DATETIME COMMENT '备注',
    INDEX IDX_SYS_LOCK_CREATE_DATE (CREATE_DATE)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT ='系统锁';
