-- 创建自增序列（oracle 11g及以下版本使用，12c+可省略并改用identity）
create
sequence seq_sys_e4j_jdbc_reg_data
    start
with 1
    increment by 1
    nocache
    nocycle;

-- 注册表 sys_e4j_jdbc_reg_data
create table sys_e4j_jdbc_reg_data
(
    id               number(19) primary key,
    data_key         varchar2(2000),
    data_value       clob,
    data_type        varchar2(1),
    create_date      timestamp,
    last_update_date timestamp
);

-- 表注释
comment on table sys_e4j_jdbc_reg_data is '注册表';

-- 字段注释
comment on column sys_e4j_jdbc_reg_data.id is '主键 自增';
comment on column sys_e4j_jdbc_reg_data.data_key is '键值key';
comment on column sys_e4j_jdbc_reg_data.data_value is '键值value';
comment on column sys_e4j_jdbc_reg_data.data_type is '数据类型 临时节点 0，存储节点 1';
comment on column sys_e4j_jdbc_reg_data.create_date is '创建时间';
comment on column sys_e4j_jdbc_reg_data.last_update_date is '更新时间';

-- 自增触发器（oracle 11g及以下版本使用，12c+可省略）
create trigger trg_sys_e4j_jdbc_reg_data
    before insert
    on sys_e4j_jdbc_reg_data
    for each row
    when
(new.id is null)
begin
select seq_sys_e4j_jdbc_reg_data.nextval
into :new.id
from dual;
end;
/

-- 给data_key创建索引
create unique index idx_sys_e4j_jdbc_reg_data_data_key on sys_e4j_jdbc_reg_data (data_key);

-- 给data_type创建索引
create index idx_sys_e4j_jdbc_reg_data_data_type on sys_e4j_jdbc_reg_data (data_type);



-- oracle 12c+ 简化版（无需序列/触发器）
/*
create table sys_e4j_jdbc_reg_data (
    id number(19) generated by default as identity primary key comment '主键 自增',
    data_key varchar2(2000) comment '键值key',
    data_value clob comment '键值value',
    data_type varchar2(1) comment '数据类型 临时节点 0，存储节点 1',
    create_date timestamp comment '创建时间',
    last_update_date timestamp comment '更新时间'
);
comment on table sys_e4j_jdbc_reg_data is '注册表';
create index idx_sys_e4j_jdbc_reg_data_data_key on sys_e4j_jdbc_reg_data(data_key);
create index idx_sys_e4j_jdbc_reg_data_data_type on sys_e4j_jdbc_reg_data(data_type);
*/