-- 创建自增序列（Oracle 11g及以下版本使用，12c+可省略并改用IDENTITY）
CREATE
    SEQUENCE seq_sys_e4j_jdbc_reg_data
    START
        WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 注册表 sys_e4j_jdbc_reg_data
CREATE TABLE sys_e4j_jdbc_reg_data
(
    id               NUMBER(19) PRIMARY KEY,
    data_key         VARCHAR2(2000),
    data_value       CLOB,
    data_type        VARCHAR2(1),
    create_date      TIMESTAMP,
    last_update_date TIMESTAMP
);

-- 表注释
COMMENT ON TABLE sys_e4j_jdbc_reg_data IS '注册表';

-- 字段注释
COMMENT ON COLUMN sys_e4j_jdbc_reg_data.id IS '主键 自增';
COMMENT ON COLUMN sys_e4j_jdbc_reg_data.data_key IS '键值key';
COMMENT ON COLUMN sys_e4j_jdbc_reg_data.data_value IS '键值value';
COMMENT ON COLUMN sys_e4j_jdbc_reg_data.data_type IS '数据类型 临时节点 0，存储节点 1';
COMMENT ON COLUMN sys_e4j_jdbc_reg_data.create_date IS '创建时间';
COMMENT ON COLUMN sys_e4j_jdbc_reg_data.last_update_date IS '更新时间';

-- 自增触发器（Oracle 11g及以下版本使用，12c+可省略）
CREATE TRIGGER trg_sys_e4j_jdbc_reg_data
    BEFORE INSERT
    ON sys_e4j_jdbc_reg_data
    FOR EACH ROW
    WHEN
        (NEW.id IS NULL)
BEGIN
    SELECT seq_sys_e4j_jdbc_reg_data.NEXTVAL
    INTO :NEW.id
    FROM DUAL;
END;
/

-- 给data_key创建索引
CREATE INDEX idx_sys_e4j_jdbc_reg_data_data_key ON sys_e4j_jdbc_reg_data (data_key);

-- 给data_type创建索引
CREATE INDEX idx_sys_e4j_jdbc_reg_data_data_type ON sys_e4j_jdbc_reg_data (data_type);



-- Oracle 12c+ 简化版（无需序列/触发器）
/*
CREATE TABLE sys_e4j_jdbc_reg_data (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '主键 自增',
    data_key VARCHAR2(2000) COMMENT '键值key',
    data_value CLOB COMMENT '键值value',
    data_type VARCHAR2(1) COMMENT '数据类型 临时节点 0，存储节点 1',
    create_date TIMESTAMP COMMENT '创建时间',
    last_update_date TIMESTAMP COMMENT '更新时间'
);
COMMENT ON TABLE sys_e4j_jdbc_reg_data IS '注册表';
CREATE INDEX idx_sys_e4j_jdbc_reg_data_data_key ON sys_e4j_jdbc_reg_data(data_key);
CREATE INDEX idx_sys_e4j_jdbc_reg_data_data_type ON sys_e4j_jdbc_reg_data(data_type);
*/