CREATE TABLE ACCOUNT
(
    PAT_ID      VARCHAR(36) PRIMARY KEY COMMENT '患者ID',
    BALANCE     INT COMMENT '余额'
);


INSERT INTO   ACCOUNT (PAT_ID, BALANCE) VALUES ('A01',10000);
INSERT INTO   ACCOUNT (PAT_ID, BALANCE) VALUES ('A02',10000);