CREATE TABLE SYS_KEY_IDEMPOTENT
(
    "IDE_KEY"   VARCHAR(128) NOT NULL,
    EXPIRE_DATE TIMESTAMP    NOT NULL,
    CONSTRAINT SYS_KEY_IDEMPOTENT_PK PRIMARY KEY ("IDE_KEY")
);

-- 添加字段备注
COMMENT ON COLUMN SYS_KEY_IDEMPOTENT."IDE_KEY" IS '业务key';
COMMENT ON COLUMN SYS_KEY_IDEMPOTENT.EXPIRE_DATE IS '过期时间';