CREATE TABLE `LEAF_ALLOC`
(
    `BIZ_TAG`     VARCHAR(128) NOT NULL DEFAULT '' COMMENT '业务key',
    `MAX_ID`      BIGINT(20)   NOT NULL DEFAULT '1' COMMENT '当前已经分配了的最大id',
    `STEP`        INT(11)      NOT NULL COMMENT '初始步长，也是动态调整的最小步长',
    `DESCRIPTION` VARCHAR(256)          DEFAULT NULL COMMENT '业务key的描述',
    `UPDATE_TIME` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`BIZ_TAG`)
) ENGINE = INNODB;
