CREATE TABLE ADVICE_STORAGE
(
    ORD_CODE VARCHAR(36) PRIMARY KEY COMMENT '项目代码',
    COUNT    INT COMMENT '库存余额',
    PRICE    INT COMMENT '单价'
);

INSERT INTO   ADVICE_STORAGE (ORD_CODE, COUNT,PRICE) VALUES ('B01',10000,20);
INSERT INTO   ADVICE_STORAGE (ORD_CODE, COUNT,PRICE) VALUES ('B02',10000,30);
INSERT INTO   ADVICE_STORAGE (ORD_CODE, COUNT,PRICE) VALUES ('B03',10000,40);
INSERT INTO   ADVICE_STORAGE (ORD_CODE, COUNT,PRICE) VALUES ('B04',10000,50);